/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    About: typeof import('./src/components/About/index.vue')['default']
    Article: typeof import('./src/components/Article/index.vue')['default']
    Articles: typeof import('./src/components/Articles/index.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    MyComp1: typeof import('./src/components/MyComp1.vue')['default']
    MyComp2: typeof import('./src/components/MyComp2.vue')['default']
    MyComp3: typeof import('./src/components/MyComp3.vue')['default']
    MyFirebaseFood: typeof import('./src/components/MyFirebaseFood.vue')['default']
    MyPrice: typeof import('./src/components/MyPrice.vue')['default']
    Price: typeof import('./src/components/Price/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    Vue3: typeof import('./src/components/Vue3/index.vue')['default']
  }
}
